[package]
name = "numstat_parser"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.75"
chrono = "0.4.30"
clap = { version = "4.4.3", features = ["derive"] }
log = "0.4.20"
rayon = "1.7.0"
regex = "1.9.5"
tempfile = "3.8.0"

[dev-dependencies]
assert_cmd = "2.0.12"
indoc = "2.0.3"
predicates = "2.1.5"
