[package]
name = "numstat_parser"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.68"
chrono = "0.4.23"
clap = { version = "4.1.1", features = ["derive"] }
regex = "1.7.1"

[dev-dependencies]
assert_cmd = "2.0.8"
indoc = "1.0.8"
predicates = "2.1.5"
tempfile = "3.3.0"
