[package]
name = "girs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
numstat_parser = { path = "../numstat-parser" }
anyhow = "1.0.75"
chrono = "0.4.31"
clap = { version = "4.4.6", features = ["derive"] }
env_logger = "0.10.0"
regex = "1.10.0"
polars = { version = "0.33.2", features = ["sql", "lazy", "rows", "is_in", "fmt", "describe", "serde", "strings"] }
rayon = "1.8.0"
log = "0.4.20"
serde_json = "1.0.107"

[dev-dependencies]
assert_cmd = "2.0.12"
predicates = "3.0.4"
tempfile = "3.8.0"
