name: duyetbot

on:
  pull_request:
    types: [opened]
  issue_comment:
    types: [created, edited]

jobs:
  duyetbot:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - env:
          comment: ${{ github.event.comment.body }}
        if: ${{ startsWith(env.comment, '@duyetbot') }}
        run: ./.github/workflows/duyetbot.sh ${{ env.comment }}
