name: duyetbot

on:
  pull_request:
    types: [opened]
  issue_comment:
    types: [created, edited]

jobs:
  duyetbot:
    runs-on: ubuntu-latest
    env:
      issue_id: ${{ github.event.issue.number }}
      src_comment: ${{ github.event.comment.body }}
      src_comment_id: ${{ github.event.comment.id }}
      src_comment_url: ${{ github.event.comment.html_url }}
      user_login: ${{ github.event.comment.user.login }}
      sender: ${{ github.event.sender.login }}

    steps:
      - uses: actions/checkout@v4
      - uses: Swatinem/rust-cache@v2

      - if: ${{ startsWith(env.src_comment, '@duyetbot ') }}
        id: call_me_babe
        run: |
          URL=$(echo ${{ env.src_comment }} | sed 's/@duyetbot //')

          echo "Validating URL: ${URL}"
          curl --head --fail ${URL}
          if [ $? -ne 0 ]; then
            echo "ok=0" >> $GITHUB_ENV
            echo "reason=invalid_url" >> $GITHUB_ENV
          else
            echo "ok=1" >> $GITHUB_ENV
            echo "github_url=$URL" >> $GITHUB_ENV
          fi

      - name: Find Comment
        uses: peter-evans/find-comment@v2
        if: ${{ env.ok == '1' }}
        id: fc
        with:
          issue-number: ${{ env.issue_id }}
          comment-author: duyetbot
          body-includes: "<!-- src_comment_id: ${{ env.src_comment_id }} -->"

      - name: That is invalid URL
        if: ${{ env.ok == '0' && env.reason == 'invalid_url' }}
        uses: jungwinter/comment@v1
        with:
          type: ${{ steps.fc.outputs.comment-id == 0 && 'create' || 'edit' }}
          comment_id: ${{ steps.fc.outputs.comment-id }}
          issue_number: ${{ env.issue_id }}
          token: ${{ secrets.DUYETBOT_TOKEN }}
          body: |
            <!-- src_comment_id: ${{ env.src_comment_id }} -->
            Replied ${{ env.src_comment_url }} to @${{ env.sender }} 

            > ${{ env.src_comment }}

            Hi ${{ env.sender }}, this is invalid: `${{ env.src_comment }}`

      - name: Process it
        if: ${{ env.ok == '1' }}
        uses: jungwinter/comment@v1
        id: comment_process
        with:
          type: ${{ steps.fc.outputs.comment-id == 0 && 'create' || 'edit' }}
          comment_id: ${{ steps.fc.outputs.comment-id }}
          issue_number: ${{ env.issue_id }}
          token: ${{ secrets.DUYETBOT_TOKEN }}
          body: |
            <!-- src_comment_id: ${{ env.src_comment_id }} -->
            Replied ${{ env.src_comment_url }} to @${{ env.sender }} 

            > ${{ env.src_comment }}

            Got it @${{ env.sender }}, please wait for me to process ${{ env.github_url }} ...

      - if: ${{ env.ok == '1' }}
        run: ./.github/workflows/duyetbot.sh ${{ env.src_comment }}

      - name: Done
        if: ${{ env.ok == '1' }}
        uses: jungwinter/comment@v1
        with:
          type: edit
          comment_id: ${{ steps.comment_process.outputs.id }}
          issue_number: ${{ env.issue_id }}
          token: ${{ secrets.DUYETBOT_TOKEN }}
          body: |
            <!-- src_comment_id: ${{ env.src_comment_id }} -->
            Replied ${{ env.src_comment_url }} to @${{ env.sender }} 

            > ${{ env.src_comment }}

            <details>
            <summary>Click to toggle the result</summary>

            ```
            ${{ env.OUTPUT }}
            ```

            </details>

